### ISSUE TITLE
Choose data from date picker

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#27] opened 2019-05-27 11:46 UTC
In the following questions it is only possible to choose a data from a date picker. But most of the time it is not possible to give a fixed date for the publication (and not all the data will archived/published at the same date). Perhaps it is more useful to give them an empty line to enter a date oder a comment like „one year after the project“?

„Wann werden die Daten veröffentlicht?“
„Bis wann werden die (unanonymisierten bzw. unpseudonymisierten) Originaldaten spätestens sicher vernichtet?“
„Wann werden die Daten archiviert?“

**Comment by jmfrenzel** [comment] 2019-05-27 12:05
There was a longer discussion on what to provide. 
For the moment we decided to stick with what comes with the rdmo-catalog , i.e. date picker.  
To allow for relative dates we would do some dev work. 
I could think of allowing to define a duration relative to `project start` or `project end` date. While the latter may be defined by  `project start` and project duration.

**Comment by Bassbiest** [comment] 2019-05-28 08:25
I will close this issue as this is working as intended.

**Closed as completed by Bassbiest** 2019-05-28 08:25 UTC
