### ISSUE TITLE
numbers in views are shown in full double precision

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#32] opened 2019-05-27 13:58 UTC
Outside of answering the questions: Button „Antworten anzeigen“
Nearly all answers in the section „costs“ with person months are like „0.7000000000000001 PM“. 
In the question with the slide controller Ichoose here for example „0.7“. 
Was this my fault at answering the question? how can I avoid that?

**Comment by Bassbiest** [comment] 2019-06-03 08:56
The problem was reported to the RDMO-Team. They confirmed it and are now working on it. Therefore, I am closing this issue.

**Closed as completed by Bassbiest** 2019-06-03 08:56 UTC
Labels: bug, rdmo
